/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tddJunit;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void verificarSaldoDespuesRealizarDeposito(){
        Account account = new Account();
        account.deposit(500);
        account.deposit(300);
        Integer balance= account.getBalance();
        assertEquals(500,balance,0);


    }

}
